/**
 * src/lib/conjugations.ts
 *
 * Static lookup module backed by src/data/es-conjugations.json.
 * Generated by scripts/generate-conjugation-table.ts — re-run that script
 * to refresh the data (e.g. to add more verbs).
 *
 * Exports:
 *   getConjugations(infinitive)  → VerbFormEntry[] | null
 *   getInfinitive(form)          → string | null
 *
 * Both lookups are O(1) / O(n forms) and require no API calls.
 * The reverse lookup stores only the *first* infinitive that produced a given
 * surface form; ambiguous forms (where two verbs share a conjugated form) are
 * rare enough that the primary match is correct in practice.
 */

import data from '../data/es-conjugations.json' with { type: 'json' }

export interface VerbFormEntry {
  form: string        // lowercase surface form, e.g. "hizo"
  translation: string // e.g. "Preterite: he/she/it did"
}

type ConjugationData = Record<string, VerbFormEntry[]>

const conjugations = data as ConjugationData

// Build reverse lookup: form → infinitive (built once at module load)
const formToInfinitive = new Map<string, string>()
for (const [infinitive, forms] of Object.entries(conjugations)) {
  for (const { form } of forms) {
    if (!formToInfinitive.has(form)) {
      formToInfinitive.set(form, infinitive)
    }
  }
  // Also register the infinitive itself
  if (!formToInfinitive.has(infinitive)) {
    formToInfinitive.set(infinitive, infinitive)
  }
}

/**
 * Returns the full conjugation table for a known infinitive, or null if the
 * verb is not in the static dataset (caller should fall back to Gemini).
 */
export function getConjugations(infinitive: string): VerbFormEntry[] | null {
  return conjugations[infinitive.toLowerCase().trim()] ?? null
}

/**
 * Resolves a conjugated surface form to its infinitive using the reverse
 * lookup table, or returns null if the form is not in the dataset.
 */
export function getInfinitive(form: string): string | null {
  return formToInfinitive.get(form.toLowerCase().trim()) ?? null
}
